// Generated from reviewed Lucide 1.51.0. ISC / Feather-derived MIT: see NOTICE.
import {
  AI_ICON,
  ALERT_ICON,
  CARD_ICON,
  CHAT_ICON,
  CHECK_ICON,
  CLOSE_ICON,
  COIN_ICON,
  COMPASS_ICON,
  COPY_ICON,
  CROWN_ICON,
  ENERGY_ICON,
  GEM_ICON,
  GIFT_ICON,
  GLOBE_ICON,
  HISTORY_ICON,
  REDO_ICON,
  UNDO_ICON,
  HOME_ICON,
  HOURGLASS_ICON,
  LAUREL_ICON,
  LOCK_ICON,
  LUCKY_ICON,
  MAIL_ICON,
  MEDAL_ICON,
  MISSION_ICON,
  MOBILE_ICON,
  PORTAL_ICON,
  SCROLL_ICON,
  SETTINGS_ICON,
  SHIRT_ICON,
  SHOP_ICON,
  SMILE_ICON,
  TIMER_ICON,
  TROPHY_ICON,
  VOTE_ICON,
  ARROW_LEFT_ICON,
  ARROW_RIGHT_ICON,
  CHEVRON_DOWN_ICON,
  CHEVRON_UP_ICON,
  DOWNLOAD_ICON,
  EXTERNAL_ICON,
  MENU_ICON,
  MINUS_ICON,
  MOON_ICON,
  PLUS_ICON,
  SEARCH_ICON,
  SUN_ICON,
  USER_ICON,
} from './paths';

export const GAME_ICONS = {
  ai: AI_ICON,
  alert: ALERT_ICON,
  card: CARD_ICON,
  chat: CHAT_ICON,
  check: CHECK_ICON,
  close: CLOSE_ICON,
  coin: COIN_ICON,
  compass: COMPASS_ICON,
  copy: COPY_ICON,
  crown: CROWN_ICON,
  energy: ENERGY_ICON,
  gem: GEM_ICON,
  gift: GIFT_ICON,
  globe: GLOBE_ICON,
  history: HISTORY_ICON,
  redo: REDO_ICON,
  undo: UNDO_ICON,
  home: HOME_ICON,
  hourglass: HOURGLASS_ICON,
  laurel: LAUREL_ICON,
  lock: LOCK_ICON,
  lucky: LUCKY_ICON,
  mail: MAIL_ICON,
  medal: MEDAL_ICON,
  mission: MISSION_ICON,
  mobile: MOBILE_ICON,
  portal: PORTAL_ICON,
  scroll: SCROLL_ICON,
  settings: SETTINGS_ICON,
  shirt: SHIRT_ICON,
  shop: SHOP_ICON,
  smile: SMILE_ICON,
  timer: TIMER_ICON,
  trophy: TROPHY_ICON,
  vote: VOTE_ICON,
  'arrow-left': ARROW_LEFT_ICON,
  'arrow-right': ARROW_RIGHT_ICON,
  'chevron-down': CHEVRON_DOWN_ICON,
  'chevron-up': CHEVRON_UP_ICON,
  download: DOWNLOAD_ICON,
  external: EXTERNAL_ICON,
  menu: MENU_ICON,
  minus: MINUS_ICON,
  moon: MOON_ICON,
  plus: PLUS_ICON,
  search: SEARCH_ICON,
  sun: SUN_ICON,
  user: USER_ICON,
} as const;
export type GameIconName = keyof typeof GAME_ICONS;
export const GAME_ICON_NAMES = Object.keys(GAME_ICONS) as GameIconName[];
