"""Deterministic, licensed Chinese webfont slices; no network or global install.

Use the exact tool versions in scripts/zh-font-source.json. Supply the extracted
upstream archive directory; output defaults to src/tokens/fonts/zh. To prove
reproducibility, rebuild into an empty ignored directory and compare hashes.
"""
from pathlib import Path
from collections import defaultdict
from importlib.metadata import version
import argparse
import hashlib
import json
import sys
from fontTools import subset
from fontTools.ttLib import TTFont


def digest(data):
    return hashlib.sha256(data).hexdigest()


def build(root, source, output):
    contract = json.loads((root / 'scripts/zh-font-source.json').read_text())
    assert version('fonttools') == contract['tools']['fonttools']
    assert version('brotli') == contract['tools']['brotli']
    assert '.'.join(map(str, sys.version_info[:3])) == contract['tools']['python']
    output = output.resolve()
    assert output.is_relative_to(root) and not output.is_symlink()
    output.mkdir(parents=True, exist_ok=True)
    family = contract['family']
    rows, css = [], []
    for entry in contract['sources']:
        filename = source / entry['filename']
        assert digest(filename.read_bytes()) == entry['sha256'], entry['filename']
        with TTFont(filename, recalcTimestamp=False) as font:
            groups = defaultdict(list)
            for codepoint in sorted(font.getBestCmap()):
                if codepoint >= contract['minUnicode']:
                    groups[codepoint // contract['blockSize']].append(codepoint)
            original_copyright = font['name'].getDebugName(0)
        for block, codepoints in sorted(groups.items()):
            first, last = min(codepoints), max(codepoints)
            name = f"{entry['weight']}-{block * contract['blockSize']:x}.woff2"
            font = TTFont(filename, recalcTimestamp=False)
            options = subset.Options()
            options.recalc_timestamp = False
            options.harfbuzz_repacker = False
            options.name_IDs = ['*']
            options.name_languages = ['*']
            options.name_legacy = True
            options.layout_features = ['*']
            options.ignore_missing_unicodes = False
            cutter = subset.Subsetter(options=options)
            cutter.populate(unicodes=codepoints)
            cutter.subset(font)
            # Rename every primary/internal family identifier after subsetting,
            # retaining copyright and OFL fields, including the upstream RFN.
            identifiers = {
                1: family, 2: entry['style'],
                3: f"{family} {entry['style']} 0.990 subset {block:x}",
                4: f"{family} {entry['style']}",
                6: f"SwimmerRoundedCN-{entry['style']}-{block:x}",
                16: family, 17: entry['style'], 18: f"{family} {entry['style']}",
                21: family, 22: entry['style'],
            }
            for record in font['name'].names:
                if record.nameID in identifiers:
                    record.string = identifiers[record.nameID].encode(record.getEncoding())
            assert font['name'].getDebugName(0) == original_copyright
            assert 'Open Font License' in font['name'].getDebugName(13)
            font['head'].modified = contract['timestamp']
            font.flavor = 'woff2'
            destination = output / name
            font.save(destination, reorderTables=True)
            font.close()
            with TTFont(destination, recalcTimestamp=False) as checked:
                assert set(checked.getBestCmap()) == set(codepoints), name
                assert checked['name'].getDebugName(1) == family
            data = destination.read_bytes()
            unicode_range = f'U+{first:X}-{last:X}'
            rows.append({'file': name, 'weight': entry['cssWeight'], 'unicodeRange': unicode_range,
                         'codepoints': len(codepoints), 'bytes': len(data), 'sha256': digest(data)})
            css.append(f"@font-face {{\n  font-family: '{family}';\n  font-style: normal;\n  font-weight: {entry['cssWeight']};\n  font-display: swap;\n  src: url('./{name}') format('woff2');\n  unicode-range: {unicode_range};\n}}")
        print(f"{entry['style']}: {len(groups)} chunks", flush=True)
    (output/'font-faces.css').write_text('/* Generated by scripts/build-zh-fonts.py; OFL-1.1. */\n'+'\n\n'.join(css)+'\n')
    manifest = {'family':family, 'sourceArchiveSha256':contract['archiveSha256'], 'tools':contract['tools'],
                'partition':{'blockSize':contract['blockSize'],'minUnicode':contract['minUnicode']},
                'chunks':rows, 'totalBytes':sum(row['bytes'] for row in rows)}
    (output/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    assert set(p.name for p in output.iterdir()) <= {row['file'] for row in rows}|{'font-faces.css','manifest.json','OFL.txt'}
    print(json.dumps({'chunks':len(rows),'bytes':manifest['totalBytes'],'family':family}))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('source',type=Path)
    parser.add_argument('--output',type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    build(root,args.source.resolve(),args.output or root/'src/tokens/fonts/zh')
