export {
  CLAY_ASSET_SIZE_TOKENS,
  CLAY_COLOR_TOKENS,
  CLAY_ELEVATION_TOKENS,
  CLAY_LAYER_TOKENS,
  CLAY_MOTION_TOKENS,
  CLAY_RADIUS_TOKENS,
  CLAY_SEMANTIC_TOKENS,
  CLAY_SPACE_TOKENS,
  CLAY_TARGET_TOKENS,
  CLAY_TYPE_TOKENS,
  CLAY_UI_TOKENS,
  type ClayTokenCategory,
} from './clay/tokens';

import {
  CLAY_ASSET_SIZE_TOKENS,
  CLAY_ELEVATION_TOKENS,
  CLAY_LAYER_TOKENS,
  CLAY_MOTION_TOKENS,
  CLAY_RADIUS_TOKENS,
  CLAY_SEMANTIC_TOKENS,
  CLAY_SPACE_TOKENS,
  CLAY_TARGET_TOKENS,
  CLAY_TYPE_TOKENS,
} from './clay/tokens';

export const GAME_UI_TOKENS = {
  ...CLAY_SEMANTIC_TOKENS,
  ...CLAY_TYPE_TOKENS,
  ...CLAY_SPACE_TOKENS,
  ...CLAY_RADIUS_TOKENS,
  ...CLAY_ELEVATION_TOKENS,
  ...CLAY_MOTION_TOKENS,
  ...CLAY_LAYER_TOKENS,
  ...CLAY_ASSET_SIZE_TOKENS,
} as const;

export const GAME_UI_TARGETS = CLAY_TARGET_TOKENS;
